;;设置系统的编码，避免各处的乱码
(prefer-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(setq default-buffer-file-coding-system 'utf-8)
;;默认字体
;; Auto generated by cnfonts
 (set-face-attribute 'default nil :font "等距更纱黑体 SC 16")
(provide 'init-ui-font)
